# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/image_tagger.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/image_tagger.proto',
  package='ImageTagger',
  syntax='proto3',
  serialized_options=_b('\252\002\021ImageTaggerClient'),
  serialized_pb=_b('\n\x19protos/image_tagger.proto\x12\x0bImageTagger\"#\n\x0fTagImageRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"\x85\x02\n\rTagImageReply\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.ImageTagger.TagImageReply.TagImageItem\x1a\xbb\x01\n\x0cTagImageItem\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x12H\n\x0b\x62oundingBox\x18\x03 \x01(\x0b\x32\x33.ImageTagger.TagImageReply.TagImageItem.BoundingBox\x1a\x45\n\x0b\x42oundingBox\x12\x0c\n\x04minX\x18\x01 \x01(\x01\x12\x0c\n\x04minY\x18\x02 \x01(\x01\x12\x0c\n\x04maxX\x18\x03 \x01(\x01\x12\x0c\n\x04maxY\x18\x04 \x01(\x01\x32S\n\x0bImageTagger\x12\x44\n\x08TagImage\x12\x1c.ImageTagger.TagImageRequest\x1a\x1a.ImageTagger.TagImageReplyB\x14\xaa\x02\x11ImageTaggerClientb\x06proto3')
)




_TAGIMAGEREQUEST = _descriptor.Descriptor(
  name='TagImageRequest',
  full_name='ImageTagger.TagImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='ImageTagger.TagImageRequest.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=77,
)


_TAGIMAGEREPLY_TAGIMAGEITEM_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='ImageTagger.TagImageReply.TagImageItem.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minX', full_name='ImageTagger.TagImageReply.TagImageItem.BoundingBox.minX', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minY', full_name='ImageTagger.TagImageReply.TagImageItem.BoundingBox.minY', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxX', full_name='ImageTagger.TagImageReply.TagImageItem.BoundingBox.maxX', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxY', full_name='ImageTagger.TagImageReply.TagImageItem.BoundingBox.maxY', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=341,
)

_TAGIMAGEREPLY_TAGIMAGEITEM = _descriptor.Descriptor(
  name='TagImageItem',
  full_name='ImageTagger.TagImageReply.TagImageItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='ImageTagger.TagImageReply.TagImageItem.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='ImageTagger.TagImageReply.TagImageItem.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boundingBox', full_name='ImageTagger.TagImageReply.TagImageItem.boundingBox', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TAGIMAGEREPLY_TAGIMAGEITEM_BOUNDINGBOX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=341,
)

_TAGIMAGEREPLY = _descriptor.Descriptor(
  name='TagImageReply',
  full_name='ImageTagger.TagImageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ImageTagger.TagImageReply.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TAGIMAGEREPLY_TAGIMAGEITEM, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=341,
)

_TAGIMAGEREPLY_TAGIMAGEITEM_BOUNDINGBOX.containing_type = _TAGIMAGEREPLY_TAGIMAGEITEM
_TAGIMAGEREPLY_TAGIMAGEITEM.fields_by_name['boundingBox'].message_type = _TAGIMAGEREPLY_TAGIMAGEITEM_BOUNDINGBOX
_TAGIMAGEREPLY_TAGIMAGEITEM.containing_type = _TAGIMAGEREPLY
_TAGIMAGEREPLY.fields_by_name['items'].message_type = _TAGIMAGEREPLY_TAGIMAGEITEM
DESCRIPTOR.message_types_by_name['TagImageRequest'] = _TAGIMAGEREQUEST
DESCRIPTOR.message_types_by_name['TagImageReply'] = _TAGIMAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TagImageRequest = _reflection.GeneratedProtocolMessageType('TagImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _TAGIMAGEREQUEST,
  '__module__' : 'protos.image_tagger_pb2'
  # @@protoc_insertion_point(class_scope:ImageTagger.TagImageRequest)
  })
_sym_db.RegisterMessage(TagImageRequest)

TagImageReply = _reflection.GeneratedProtocolMessageType('TagImageReply', (_message.Message,), {

  'TagImageItem' : _reflection.GeneratedProtocolMessageType('TagImageItem', (_message.Message,), {

    'BoundingBox' : _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
      'DESCRIPTOR' : _TAGIMAGEREPLY_TAGIMAGEITEM_BOUNDINGBOX,
      '__module__' : 'protos.image_tagger_pb2'
      # @@protoc_insertion_point(class_scope:ImageTagger.TagImageReply.TagImageItem.BoundingBox)
      })
    ,
    'DESCRIPTOR' : _TAGIMAGEREPLY_TAGIMAGEITEM,
    '__module__' : 'protos.image_tagger_pb2'
    # @@protoc_insertion_point(class_scope:ImageTagger.TagImageReply.TagImageItem)
    })
  ,
  'DESCRIPTOR' : _TAGIMAGEREPLY,
  '__module__' : 'protos.image_tagger_pb2'
  # @@protoc_insertion_point(class_scope:ImageTagger.TagImageReply)
  })
_sym_db.RegisterMessage(TagImageReply)
_sym_db.RegisterMessage(TagImageReply.TagImageItem)
_sym_db.RegisterMessage(TagImageReply.TagImageItem.BoundingBox)


DESCRIPTOR._options = None

_IMAGETAGGER = _descriptor.ServiceDescriptor(
  name='ImageTagger',
  full_name='ImageTagger.ImageTagger',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=343,
  serialized_end=426,
  methods=[
  _descriptor.MethodDescriptor(
    name='TagImage',
    full_name='ImageTagger.ImageTagger.TagImage',
    index=0,
    containing_service=None,
    input_type=_TAGIMAGEREQUEST,
    output_type=_TAGIMAGEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGETAGGER)

DESCRIPTOR.services_by_name['ImageTagger'] = _IMAGETAGGER

# @@protoc_insertion_point(module_scope)
